import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "New Orleans Tours for Limited Mobility: What to Check Before Booking",
  description: "Compare New Orleans tour formats for limited mobility using current wheelchair, stairs, gravel, walking, boarding, and accessibility details.",
  alternates: { canonical: "/guides/new-orleans-tours-limited-mobility" },
};

export default function LimitedMobilityGuide() {
  return (
    <article className="min-h-screen bg-[#151515] text-[#fdfbf7]">
      <header className="border-b border-[#2a2a2a] bg-[#101010] px-6 py-14 md:py-20"><div className="mx-auto max-w-5xl"><p className="text-xs font-bold uppercase tracking-[0.24em] text-[#d4af37]">Accessibility decision guide</p><h1 className="mt-4 max-w-4xl font-[var(--font-accent)] text-4xl font-bold leading-tight md:text-6xl">New Orleans tours for limited mobility</h1><p className="mt-6 max-w-3xl text-lg leading-relaxed text-[#ccc]">“Accessible” is not one yes/no label. The useful questions are whether you can stay seated, whether paths are paved or gravel, whether stairs are required, whether the vehicle or vessel can accommodate equipment, and whether advance notice is required.</p><p className="mt-5 text-xs uppercase tracking-[0.16em] text-[#888]">Operator facts last checked August 9, 2026</p></div></header>
      <div className="mx-auto max-w-5xl space-y-12 px-6 py-12 md:py-16">
        <section className="overflow-x-auto"><h2 className="font-[var(--font-accent)] text-3xl font-bold">Current accessibility details that matter</h2><table className="mt-6 w-full min-w-[760px] border-collapse text-left text-sm"><thead><tr className="border-b border-[#444] text-[#d4af37]"><th className="p-3">Experience</th><th className="p-3">What the operator says</th><th className="p-3">Watch for</th></tr></thead><tbody className="text-[#ccc]"><tr className="border-b border-[#333]"><td className="p-3 font-bold text-white">City & Cemetery sightseeing</td><td className="p-3">Guests with limited mobility may remain on the bus at stops.</td><td className="p-3">Some Garden District sidewalks are uneven.</td></tr><tr className="border-b border-[#333]"><td className="p-3 font-bold text-white">Oak Alley</td><td className="p-3">Basic and motorized wheelchairs permitted; paved paths.</td><td className="p-3">Second floor of Big House requires 22 stairs; video alternative listed.</td></tr><tr className="border-b border-[#333]"><td className="p-3 font-bold text-white">Whitney</td><td className="p-3">Gift shop, restrooms and museum accessible; grounds accessible.</td><td className="p-3">Uneven gravel; slave quarters viewable but not enterable by wheelchair.</td></tr><tr className="border-b border-[#333]"><td className="p-3 font-bold text-white">75-minute riverboat</td><td className="p-3">Vessel listed as handicap accessible.</td><td className="p-3">Top deck requires stairs.</td></tr><tr><td className="p-3 font-bold text-white">Airboats</td><td className="p-3">Checked small and large airboats are not wheelchair or stroller accessible.</td><td className="p-3">Passengers must be able to board without staff assistance.</td></tr></tbody></table></section>
        <section className="border-l-4 border-[#d4af37] bg-[#1b1b1b] p-6"><h2 className="text-2xl font-bold">Advance notice can matter</h2><p className="mt-4 text-[#ccc]">Gray Line asks guests to submit special accommodation requests at least 48 hours in advance so an accessible vehicle can be supplied when possible. For swamp combinations, only one swamp boat is listed as wheelchair accessible, so advance requests matter there too.</p></section>
        <section><h2 className="font-[var(--font-accent)] text-3xl font-bold">Better starting points</h2><p className="mt-4 leading-relaxed text-[#ccc]">For someone who can transfer but cannot walk far, vehicle-based city sightseeing may be easier than a walking tour. For someone using a wheelchair, the riverboat or Oak Alley may be workable depending on equipment and which areas matter most. Airboats should not be treated as accessible substitutes.</p></section>
        <section className="border-t border-[#333] pt-8"><h2 className="text-lg font-bold">Official sources checked</h2><div className="mt-4 flex flex-wrap gap-4 text-sm"><a className="text-[#d4af37] underline" href="https://www.graylineneworleans.com/faqs/" target="_blank" rel="noopener noreferrer">Gray Line accessibility FAQ</a><a className="text-[#d4af37] underline" href="https://www.graylineneworleans.com/plantation-tours/oak-alley-plantation-tour/" target="_blank" rel="noopener noreferrer">Oak Alley</a><a className="text-[#d4af37] underline" href="https://www.graylineneworleans.com/all/swamp-and-bayou-tour/whitney-plantation-tour/" target="_blank" rel="noopener noreferrer">Whitney</a><a className="text-[#d4af37] underline" href="https://www.graylineneworleans.com/riverboat-cruises/75-minute-city-of-new-orleans-riverboat-cruise/" target="_blank" rel="noopener noreferrer">Riverboat</a></div></section>
        <nav className="border-t border-[#333] pt-8 text-sm flex flex-wrap gap-5"><Link className="text-[#d4af37] underline" href="/compare/whitney-vs-oak-alley">Whitney vs Oak Alley</Link><Link className="text-[#d4af37] underline" href="/guides/new-orleans-tours-for-grandparents-and-kids">Grandparents + kids</Link><Link className="text-[#d4af37] underline" href="/help-me-choose">Help Me Choose</Link></nav>
      </div>
    </article>
  );
}
