import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Best New Orleans Tours Under 4 or 6 Hours",
  description: "Compare New Orleans tours by real scheduled duration: 75 minutes, 2 hours, 2.5 hours, 3 hours, 3.75 hours, and about 5.5 hours.",
  alternates: { canonical: "/guides/best-new-orleans-tours-under-4-or-6-hours" },
};

export default function UnderFourOrSixHoursGuide() {
  return (
    <article className="min-h-screen bg-[#151515] text-[#fdfbf7]">
      <header className="border-b border-[#2a2a2a] bg-[#101010] px-6 py-14 md:py-20"><div className="mx-auto max-w-5xl"><p className="text-xs font-bold uppercase tracking-[0.24em] text-[#d4af37]">Time-budget guide</p><h1 className="mt-4 max-w-4xl font-[var(--font-accent)] text-4xl font-bold leading-tight md:text-6xl">Best New Orleans tours under 4 or 6 hours</h1><p className="mt-6 max-w-3xl text-lg leading-relaxed text-[#ccc]">If your day has a hard time limit, compare scheduled duration before comparing tour names. New Orleans options range from a 75-minute river cruise to roughly 5-hour-25-minute plantation outings — with several useful stops in between.</p><p className="mt-5 text-xs uppercase tracking-[0.16em] text-[#888]">Operator facts last checked August 9, 2026</p></div></header>
      <div className="mx-auto max-w-5xl space-y-12 px-6 py-12 md:py-16">
        <section className="overflow-x-auto"><table className="w-full min-w-[760px] border-collapse text-left text-sm"><thead><tr className="border-b border-[#444] text-[#d4af37]"><th className="p-3">Scheduled duration</th><th className="p-3">Example</th><th className="p-3">Best for</th></tr></thead><tbody className="text-[#ccc]"><tr className="border-b border-[#333]"><td className="p-3 font-bold text-white">75 minutes</td><td className="p-3">CITY of NEW ORLEANS sightseeing cruise</td><td className="p-3">Very short time window</td></tr><tr className="border-b border-[#333]"><td className="p-3 font-bold text-white">2 hours</td><td className="p-3">Ghosts & Spirits; standard Craft Cocktail; NATCHEZ sightseeing</td><td className="p-3">Half-day with lots of buffer</td></tr><tr className="border-b border-[#333]"><td className="p-3 font-bold text-white">2.5 hours</td><td className="p-3">Upgraded Craft Cocktail</td><td className="p-3">Adults 21+ who want a fuller evening activity</td></tr><tr className="border-b border-[#333]"><td className="p-3 font-bold text-white">3 hours</td><td className="p-3">City & Cemetery + Garden District</td><td className="p-3">Broader city sightseeing</td></tr><tr className="border-b border-[#333]"><td className="p-3 font-bold text-white">3 hours 45 minutes</td><td className="p-3">Transported swamp / airboat options</td><td className="p-3">Swamp experience without spending most of the day</td></tr><tr><td className="p-3 font-bold text-white">5 hours 25 minutes</td><td className="p-3">Whitney or Oak Alley plantation outing</td><td className="p-3">A substantial half-day / most-of-day history trip</td></tr></tbody></table></section>
        <section className="border-l-4 border-[#d4af37] bg-[#1b1b1b] p-6"><h2 className="text-2xl font-bold">Scheduled duration is not your total time commitment</h2><p className="mt-4 text-[#ccc]">Add check-in, getting to the meeting point, and a conservative buffer afterward. A three-hour listing should not be booked against a hard three-hour deadline.</p></section>
        <section><h2 className="font-[var(--font-accent)] text-3xl font-bold">If you have under four hours</h2><p className="mt-4 text-[#ccc]">Start with river cruises, ghost tours, cocktail tours, or city sightseeing. Transported swamp options sit near the four-hour line, so they are better when you have some margin.</p><h2 className="mt-8 font-[var(--font-accent)] text-3xl font-bold">If you have under six hours</h2><p className="mt-4 text-[#ccc]">Whitney and Oak Alley become realistic options at their listed 5-hour-25-minute duration, but only if your surrounding schedule has enough buffer. Seven-hour-plus combo tours are a different category.</p></section>
        <section className="border-t border-[#333] pt-8"><h2 className="text-lg font-bold">Official sources checked</h2><div className="mt-4 flex flex-wrap gap-4 text-sm"><a className="text-[#d4af37] underline" href="https://www.graylineneworleans.com/" target="_blank" rel="noopener noreferrer">Gray Line current tour durations</a><a className="text-[#d4af37] underline" href="https://www.graylineneworleans.com/haunted-city-cemetery-tours/" target="_blank" rel="noopener noreferrer">City / ghost durations</a><a className="text-[#d4af37] underline" href="https://www.graylineneworleans.com/food-drinks-tours/" target="_blank" rel="noopener noreferrer">Cocktail durations</a></div></section>
        <nav className="border-t border-[#333] pt-8 text-sm flex flex-wrap gap-5"><Link className="text-[#d4af37] underline" href="/compare/best-new-orleans-tour-if-you-only-have-3-hours">Best tour around 3 hours</Link><Link className="text-[#d4af37] underline" href="/guides/new-orleans-tours-without-an-all-day-bus-ride">Avoid an all-day bus ride</Link><Link className="text-[#d4af37] underline" href="/help-me-choose">Help Me Choose</Link></nav>
      </div>
    </article>
  );
}
