import type { MetadataRoute } from "next";
import {
  createRouteGovernanceIndex,
  type HandoffPolicy,
  type NetworkRole,
  type PublishState,
} from "./sharedRouteGovernance";

export type RouteGovernanceEntry = {
  path: string;
  publishState: PublishState;
  networkRole: NetworkRole;
  handoffPolicy: HandoffPolicy;
  priority?: number;
  changeFrequency?: MetadataRoute.Sitemap[number]["changeFrequency"];
  notes?: string;
};

const GOSNO_ROUTE_GOVERNANCE = [
  {
    path: "/",
    publishState: "promoted",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 1,
    changeFrequency: "weekly",
    notes: "Primary GoSno mountain-route intake surface.",
  },
  {
    path: "/book",
    publishState: "live_unpromoted",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    notes: "Guided continuation flow, not meant to rank independently.",
  },
  {
    path: "/destinations",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.92,
    changeFrequency: "weekly",
    notes: "Destination hub listing the operator execution pages.",
  },
  {
    path: "/services",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.8,
    changeFrequency: "monthly",
    notes: "Service hub supporting airport, return, and group lanes.",
  },
  {
    path: "/about",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.6,
    changeFrequency: "monthly",
  },
  {
    path: "/faq",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.6,
    changeFrequency: "monthly",
  },
  {
    path: "/contact",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.6,
    changeFrequency: "monthly",
  },
  {
    path: "/blog",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.55,
    changeFrequency: "monthly",
  },
  {
    path: "/airport-shuttle",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.78,
    changeFrequency: "monthly",
  },
  {
    path: "/black-hawk",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.72,
    changeFrequency: "monthly",
  },
  {
    path: "/denver-to-breckenridge",
    publishState: "promoted",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.98,
    changeFrequency: "weekly",
    notes: "Canonical Breckenridge money page preserving Denver-to-destination query intent.",
  },
  {
    path: "/denver-to-breckenridge-shuttle",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.9,
    changeFrequency: "weekly",
    notes: "Exact shuttle-intent Breckenridge entry page feeding route=breckenridge into booking.",
  },
  {
    path: "/denver-airport-to-breckenridge",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.88,
    changeFrequency: "weekly",
    notes: "DEN airport to Breckenridge entry page feeding pickup and route context into booking.",
  },
  {
    path: "/breckenridge",
    publishState: "live_unpromoted",
    networkRole: "utility",
    handoffPolicy: "bidirectional",
    notes: "Compatibility alias that redirects to canonical Denver-to-Breckenridge route.",
  },
  {
    path: "/breckenridge-shuttle",
    publishState: "live_unpromoted",
    networkRole: "utility",
    handoffPolicy: "bidirectional",
    notes: "Legacy alias route that should redirect into canonical Breckenridge path.",
  },
  {
    path: "/breckenridge/index.html",
    publishState: "live_unpromoted",
    networkRole: "utility",
    handoffPolicy: "bidirectional",
    notes: "Legacy filesystem-style alias that redirects to canonical Denver-to-Breckenridge route.",
  },
  {
    path: "/denver-to-breckenridge-transportation",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.7,
    changeFrequency: "weekly",
    notes: "Denver to Breckenridge transport options page.",
  },
  {
    path: "/denver-airport-to-breckenridge-shuttle",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.7,
    changeFrequency: "weekly",
    notes: "Denver Airport to Breckenridge private vs shared shuttle page.",
  },
  {
    path: "/breckenridge-private-shuttle",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.7,
    changeFrequency: "weekly",
    notes: "Breckenridge private shuttle service page.",
  },
  {
    path: "/denver-to-breckenridge-with-ski-gear",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.7,
    changeFrequency: "weekly",
    notes: "Denver to Breckenridge travel with ski gear guide page.",
  },
  {
    path: "/denver-to-breckenridge-winter-driving",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.7,
    changeFrequency: "weekly",
    notes: "Denver to Breckenridge winter driving tips page.",
  },
  {
    path: "/breckenridge-group-transportation",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.7,
    changeFrequency: "weekly",
    notes: "Breckenridge group transit private vans page.",
  },
  {
    path: "/breckenridge-return-shuttle-to-denver-airport",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.7,
    changeFrequency: "weekly",
    notes: "Breckenridge return shuttle to Denver Airport page.",
  },
  {
    path: "/breckenridge-ski-trip-airport-transfer",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.7,
    changeFrequency: "weekly",
    notes: "Breckenridge ski trip arrival transfer guide page.",
  },
  {
    path: "/denver-to-breckenridge-without-a-car",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.7,
    changeFrequency: "weekly",
    notes: "Getting from Denver to Breckenridge without a rental car page.",
  },
  {
    path: "/breckenridge-shuttle-faq",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.7,
    changeFrequency: "weekly",
    notes: "Breckenridge private shuttle FAQ page.",
  },
  {
    path: "/denver-airport-to-one-ski-hill-place",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.6,
    changeFrequency: "weekly",
    notes: "Denver Airport to One Ski Hill Place transfer.",
  },
  {
    path: "/colorado-springs-airport-to-one-ski-hill-place",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.6,
    changeFrequency: "weekly",
    notes: "Colorado Springs Airport to One Ski Hill Place transfer.",
  },
  {
    path: "/denver-airport-to-grand-colorado-on-peak-8",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.6,
    changeFrequency: "weekly",
    notes: "Denver Airport to Grand Colorado Peak 8 transfer.",
  },
  {
    path: "/colorado-springs-airport-to-grand-colorado-on-peak-8",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.6,
    changeFrequency: "weekly",
    notes: "Colorado Springs Airport to Grand Colorado Peak 8 transfer.",
  },
  {
    path: "/denver-airport-to-crystal-peak-lodge",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.6,
    changeFrequency: "weekly",
    notes: "Denver Airport to Crystal Peak Lodge transfer.",
  },
  {
    path: "/colorado-springs-airport-to-crystal-peak-lodge",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.6,
    changeFrequency: "weekly",
    notes: "Colorado Springs Airport to Crystal Peak Lodge transfer.",
  },
  {
    path: "/denver-airport-to-beaver-run-resort",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.6,
    changeFrequency: "weekly",
    notes: "Denver Airport to Beaver Run Resort transfer.",
  },
  {
    path: "/colorado-springs-airport-to-beaver-run-resort",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.6,
    changeFrequency: "weekly",
    notes: "Colorado Springs Airport to Beaver Run Resort transfer.",
  },
  {
    path: "/denver-airport-to-the-lodge-at-breckenridge",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.6,
    changeFrequency: "weekly",
    notes: "Denver Airport to The Lodge at Breckenridge transfer.",
  },
  {
    path: "/colorado-springs-airport-to-the-lodge-at-breckenridge",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.6,
    changeFrequency: "weekly",
    notes: "Colorado Springs Airport to The Lodge at Breckenridge transfer.",
  },
  {
    path: "/denver-airport-to-mountain-thunder-lodge",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.6,
    changeFrequency: "weekly",
    notes: "Denver Airport to Mountain Thunder Lodge transfer.",
  },
  {
    path: "/colorado-springs-airport-to-mountain-thunder-lodge",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.6,
    changeFrequency: "weekly",
    notes: "Colorado Springs Airport to Mountain Thunder Lodge transfer.",
  },
  {
    path: "/denver-airport-to-marriotts-mountain-valley-lodge",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.6,
    changeFrequency: "weekly",
    notes: "Denver Airport to Marriott Mountain Valley Lodge transfer.",
  },
  {
    path: "/colorado-springs-airport-to-marriotts-mountain-valley-lodge",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.6,
    changeFrequency: "weekly",
    notes: "Colorado Springs Airport to Marriott Mountain Valley Lodge transfer.",
  },
  {
    path: "/denver-airport-to-residence-inn-breckenridge",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.6,
    changeFrequency: "weekly",
    notes: "Denver Airport to Residence Inn Breckenridge transfer.",
  },
  {
    path: "/colorado-springs-airport-to-residence-inn-breckenridge",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.6,
    changeFrequency: "weekly",
    notes: "Colorado Springs Airport to Residence Inn Breckenridge transfer.",
  },
  {
    path: "/denver-airport-to-river-mountain-lodge",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.6,
    changeFrequency: "weekly",
    notes: "Denver Airport to River Mountain Lodge transfer.",
  },
  {
    path: "/colorado-springs-airport-to-river-mountain-lodge",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.6,
    changeFrequency: "weekly",
    notes: "Colorado Springs Airport to River Mountain Lodge transfer.",
  },
  {
    path: "/denver-airport-to-gravity-haus-breckenridge",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.6,
    changeFrequency: "weekly",
    notes: "Denver Airport to Gravity Haus Breckenridge transfer.",
  },
  {
    path: "/colorado-springs-airport-to-gravity-haus-breckenridge",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.6,
    changeFrequency: "weekly",
    notes: "Colorado Springs Airport to Gravity Haus Breckenridge transfer.",
  },
  {
    path: "/keystone",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.85,
    changeFrequency: "weekly",
  },
  {
    path: "/vail",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.9,
    changeFrequency: "weekly",
  },
  {
    path: "/denver-to-vail-shuttle",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.88,
    changeFrequency: "weekly",
    notes: "Exact Denver to Vail shuttle entry page feeding route=vail into booking.",
  },
  {
    path: "/copper",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.84,
    changeFrequency: "weekly",
    notes: "Copper Mountain execution page with clean public slug.",
  },
  {
    path: "/steamboat",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.84,
    changeFrequency: "weekly",
    notes: "Steamboat Springs execution page with clean public slug.",
  },
  {
    path: "/beaver-creek",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.8,
    changeFrequency: "weekly",
  },
  {
    path: "/winter-park",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.8,
    changeFrequency: "weekly",
  },
  {
    path: "/copper-mountain",
    publishState: "live_unpromoted",
    networkRole: "utility",
    handoffPolicy: "bidirectional",
    notes: "Legacy long-form Copper Mountain slug retained for compatibility.",
  },
  {
    path: "/aspen",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.85,
    changeFrequency: "weekly",
  },
  {
    path: "/snowmass",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.8,
    changeFrequency: "weekly",
  },
  {
    path: "/steamboat-springs",
    publishState: "live_unpromoted",
    networkRole: "utility",
    handoffPolicy: "bidirectional",
    notes: "Legacy long-form Steamboat Springs slug retained for compatibility.",
  },
  {
    path: "/services/airport-shuttle",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.64,
    changeFrequency: "monthly",
  },
  {
    path: "/denver-airport-shuttle-to-ski-resorts",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.86,
    changeFrequency: "weekly",
    notes: "Broad DEN airport to ski resorts entry page pushing users into route choice and booking.",
  },
  {
    path: "/services/return-shuttle",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.6,
    changeFrequency: "monthly",
  },
  {
    path: "/services/round-trip",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.6,
    changeFrequency: "monthly",
  },
  {
    path: "/services/black-hawk-shuttle",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.58,
    changeFrequency: "monthly",
  },
  {
    path: "/services/group-transport",
    publishState: "indexable",
    networkRole: "satellite",
    handoffPolicy: "bidirectional",
    priority: 0.58,
    changeFrequency: "monthly",
  },
  {
    path: "/privacy-policy",
    publishState: "indexable",
    networkRole: "utility",
    handoffPolicy: "bidirectional",
    priority: 0.2,
    changeFrequency: "yearly",
  },
  {
    path: "/terms-and-conditions",
    publishState: "indexable",
    networkRole: "utility",
    handoffPolicy: "bidirectional",
    priority: 0.2,
    changeFrequency: "yearly",
  },
  {
    path: "/cancellation-policy",
    publishState: "indexable",
    networkRole: "utility",
    handoffPolicy: "bidirectional",
    priority: 0.2,
    changeFrequency: "yearly",
  },
] as const satisfies readonly RouteGovernanceEntry[];

const GOSNO_ROUTE_GOVERNANCE_INDEX = createRouteGovernanceIndex(GOSNO_ROUTE_GOVERNANCE);

export const GOSNO_INDEXABLE_ROUTE_PATHS = GOSNO_ROUTE_GOVERNANCE_INDEX.indexablePaths;
export const GOSNO_VISIBLE_ROUTE_PATHS = GOSNO_ROUTE_GOVERNANCE_INDEX.visiblePaths;

export function getGosnoRouteGovernance(pathname: string): RouteGovernanceEntry | null {
  return GOSNO_ROUTE_GOVERNANCE_INDEX.get(pathname);
}

export function getGosnoRouteGovernanceEntries(): readonly RouteGovernanceEntry[] {
  return GOSNO_ROUTE_GOVERNANCE_INDEX.entries;
}
