import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Best New Orleans Tours If You Arrive at Noon",
  description: "Practical afternoon New Orleans tour options using current schedules, check-in times, duration, and meeting-point details.",
  alternates: { canonical: "/guides/best-new-orleans-tours-if-you-arrive-at-noon" },
};

export default function NoonArrivalGuide() {
  return (
    <article className="min-h-screen bg-[#151515] text-[#fdfbf7]">
      <header className="border-b border-[#2a2a2a] bg-[#101010] px-6 py-14 md:py-20"><div className="mx-auto max-w-5xl"><p className="text-xs font-bold uppercase tracking-[0.24em] text-[#d4af37]">Afternoon planning guide</p><h1 className="mt-4 max-w-4xl font-[var(--font-accent)] text-4xl font-bold leading-tight md:text-6xl">Best New Orleans tours if you arrive at noon</h1><p className="mt-6 max-w-3xl text-lg leading-relaxed text-[#ccc]">Do not book the first afternoon tour you see. Build in time to reach your hotel, drop bags, get to the meeting point, and check in. A short river cruise or evening walking tour can fit a noon arrival much more safely than a long out-of-town excursion.</p><p className="mt-5 text-xs uppercase tracking-[0.16em] text-[#888]">Schedules and operator facts last checked August 9, 2026</p></div></header>
      <div className="mx-auto max-w-5xl space-y-12 px-6 py-12 md:py-16">
        <section className="grid gap-6 md:grid-cols-3"><div className="border border-[#333] bg-[#1a1a1a] p-6"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#d4af37]">Low-friction afternoon</p><h2 className="mt-3 text-2xl font-bold">75-minute riverboat</h2><p className="mt-4 text-[#ccc]">The checked CITY of NEW ORLEANS schedule lists a 3:00 p.m. boarding for a 3:30–4:45 p.m. cruise. It asks guests to arrive 30 minutes before cruising.</p></div><div className="border border-[#333] bg-[#1a1a1a] p-6"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#d4af37]">Evening option</p><h2 className="mt-3 text-2xl font-bold">Ghosts & Spirits</h2><p className="mt-4 text-[#ccc]">The checked walking tour is two hours and asks guests to check in 15 minutes early at 400 Toulouse Street. It can leave your afternoon free to settle in.</p></div><div className="border border-[#333] bg-[#1a1a1a] p-6"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#d4af37]">Adults 21+</p><h2 className="mt-3 text-2xl font-bold">Craft Cocktail</h2><p className="mt-4 text-[#ccc]">The standard version is two hours; the upgraded version is 2.5 hours. Both checked listings start from 400 Toulouse Street and require age 21+.</p></div></section>
        <section className="border-l-4 border-[#d4af37] bg-[#1b1b1b] p-6"><h2 className="text-2xl font-bold">Do not treat “arrive at noon” as “available at noon”</h2><p className="mt-4 text-[#ccc]">Airport arrival, baggage, rideshare, hotel check-in and French Quarter traffic all consume time. This page does not promise that any specific departure is safe for your flight or train. Use a conservative buffer and confirm the exact departure before paying.</p></section>
        <section><h2 className="font-[var(--font-accent)] text-3xl font-bold">What I would skip on arrival day</h2><p className="mt-4 leading-relaxed text-[#ccc]">A 5+ hour plantation outing, a transported swamp trip, or a 7+ hour combination is a poor fit unless you are already in town well before noon. Those products make more sense on a full day when a delayed arrival cannot wreck the plan.</p></section>
        <section className="border-t border-[#333] pt-8"><h2 className="text-lg font-bold">Official sources checked</h2><div className="mt-4 flex flex-wrap gap-4 text-sm"><a className="text-[#d4af37] underline" href="https://www.graylineneworleans.com/riverboat-cruises/75-minute-city-of-new-orleans-riverboat-cruise/" target="_blank" rel="noopener noreferrer">75-minute riverboat schedule</a><a className="text-[#d4af37] underline" href="https://www.graylineneworleans.com/ghosts-spirits/" target="_blank" rel="noopener noreferrer">Ghosts & Spirits</a><a className="text-[#d4af37] underline" href="https://www.graylineneworleans.com/food-drinks-tours/new-orleans-craft-cocktail-walking-tour-2/" target="_blank" rel="noopener noreferrer">2-hour cocktail tour</a></div></section>
        <nav className="border-t border-[#333] pt-8 text-sm flex flex-wrap gap-5"><Link className="text-[#d4af37] underline" href="/compare/best-new-orleans-tour-if-you-only-have-3-hours">Only have 3 hours?</Link><Link className="text-[#d4af37] underline" href="/tours/city-of-new-orleans-riverboat-cruise">Riverboat options</Link><Link className="text-[#d4af37] underline" href="/help-me-choose">Help Me Choose</Link></nav>
      </div>
    </article>
  );
}
