import { DCC_SITE_TRUTH } from "@/lib/dcc/siteTruth";

export const DCC_SITE_CONTRACT = {
  spec: "dcc-site-contract",
  version: "1.1",
  schemaUrl: "https://www.destinationcommandcenter.com/dcc-site-contract.schema.json",
  registryUrl: "https://www.destinationcommandcenter.com/api/public/portfolio-feed",
  truthFeedUrl: "https://www.destinationcommandcenter.com/api/public/truth-feed",
} as const;

export const DCC_PORTFOLIO_SITES = DCC_SITE_TRUTH.map((record) => ({
  dcc_id: record.dcc_id,
  id: record.id,
  name: record.name,
  url: record.url,
  type: record.type,
  role: record.role,
  authority: record.authority,
  status: record.status,
  provenance: record.provenance,
  booking: record.booking,
  truth_url: `${DCC_SITE_CONTRACT.truthFeedUrl}?id=${encodeURIComponent(record.id)}`,
}));

export const DCC_PORTFOLIO_RELATIONSHIPS = [
  { from: "dcc:site:destination-command-center", relation: "indexes", to: "dcc:site:cruise-promenade" },
  { from: "dcc:site:destination-command-center", relation: "indexes", to: "dcc:site:vibe-around-town" },
  { from: "dcc:site:destination-command-center", relation: "indexes", to: "dcc:site:wno-tours" },
  { from: "dcc:site:destination-command-center", relation: "indexes", to: "dcc:site:gosno" },
  { from: "dcc:site:destination-command-center", relation: "indexes", to: "dcc:site:bigsky-gosno" },
  { from: "dcc:site:destination-command-center", relation: "indexes", to: "dcc:site:save-on-the-strip" },
  { from: "dcc:site:destination-command-center", relation: "indexes", to: "dcc:site:welcome-to-the-swamp" },
  { from: "dcc:site:destination-command-center", relation: "indexes", to: "dcc:site:juneau-flight-deck" },
  { from: "dcc:site:destination-command-center", relation: "indexes", to: "dcc:site:last-frontier-shore-excursions" },
  { from: "dcc:site:destination-command-center", relation: "indexes", to: "dcc:site:welcome-to-the-dells" },
  { from: "dcc:site:destination-command-center", relation: "indexes", to: "dcc:site:french-quarter-orientation" },
  { from: "dcc:site:destination-command-center", relation: "indexes", to: "dcc:site:shuttleya" },
  { from: "dcc:site:destination-command-center", relation: "indexes", to: "dcc:site:420-friendly-airport-pickup" },
  { from: "dcc:site:bigsky-gosno", relation: "related_service", to: "dcc:site:gosno" },
  { from: "dcc:site:wno-tours", relation: "serves_destination", to: "dcc:destination:new-orleans" },
  { from: "dcc:site:welcome-to-the-swamp", relation: "serves_destination", to: "dcc:destination:new-orleans" },
  { from: "dcc:site:french-quarter-orientation", relation: "serves_destination", to: "dcc:destination:new-orleans" },
  { from: "dcc:site:vibe-around-town", relation: "serves_destination", to: "dcc:destination:st-thomas" },
  { from: "dcc:site:vibe-around-town", relation: "serves_destination", to: "dcc:destination:st-john" },
  { from: "dcc:site:vibe-around-town", relation: "serves_destination", to: "dcc:destination:st-croix" },
  { from: "dcc:site:save-on-the-strip", relation: "serves_destination", to: "dcc:destination:las-vegas" },
  { from: "dcc:site:juneau-flight-deck", relation: "serves_destination", to: "dcc:destination:juneau" },
  { from: "dcc:site:last-frontier-shore-excursions", relation: "serves_region", to: "dcc:region:alaska" },
  { from: "dcc:site:welcome-to-the-dells", relation: "serves_destination", to: "dcc:destination:wisconsin-dells" },
  { from: "dcc:site:gosno", relation: "serves_airport", to: "dcc:airport:den" },
  { from: "dcc:site:gosno", relation: "serves_airport", to: "dcc:airport:cos" },
  { from: "dcc:site:bigsky-gosno", relation: "serves_airport", to: "dcc:airport:bzn" },
  { from: "dcc:site:bigsky-gosno", relation: "serves_destination", to: "dcc:destination:big-sky-montana" },
  { from: "dcc:site:420-friendly-airport-pickup", relation: "serves_airport", to: "dcc:airport:den" },
  { from: "dcc:site:420-friendly-airport-pickup", relation: "related_service", to: "dcc:site:gosno" },
] as const;
