export const DCC_SITE_CONTRACT = {
  spec: "dcc-site-contract",
  version: "1.0",
  registryUrl: "https://www.destinationcommandcenter.com/api/public/portfolio-feed",
} as const;

export const DCC_PORTFOLIO_SITES = [
  {
    dcc_id: "dcc:site:destination-command-center",
    id: "destination-command-center",
    name: "Destination Command Center",
    url: "https://www.destinationcommandcenter.com",
    type: "location_intelligence_graph",
    authority: ["coordinate_identity", "public_location_context", "portfolio_relationships"],
  },
  {
    dcc_id: "dcc:site:cruise-promenade",
    id: "cruise-promenade",
    name: "Cruise Promenade",
    url: "https://cruisepromenade.com",
    type: "cruise_group_planner",
    authority: ["cruise_planning", "ship_and_sailing_context", "shared_private_plans"],
  },
  {
    dcc_id: "dcc:site:vibe-around-town",
    id: "vibe-around-town",
    name: "Vibe Around Town",
    url: "https://vibearoundtown.com",
    type: "private_local_driver_marketplace",
    authority: ["driver_profiles", "vehicle_profiles", "request_and_accept_booking_state"],
  },
  {
    dcc_id: "dcc:site:wno-tours",
    id: "wno-tours",
    name: "Welcome to New Orleans Tours",
    url: "https://www.welcometoneworleanstours.com",
    type: "tour_recommendation_service",
    authority: ["tour_recommendations", "tour_decision_guides", "participating_operator_handoffs"],
  },
  {
    dcc_id: "dcc:site:gosno",
    id: "gosno",
    name: "GoSno",
    url: "https://gosno.co",
    type: "private_mountain_transportation",
    authority: ["service_routes", "published_transfer_pricing", "vehicle_service_options"],
  },
  {
    dcc_id: "dcc:site:bigsky-gosno",
    id: "bigsky-gosno",
    name: "Big Sky GoSno",
    url: "https://bigsky.gosno.co",
    type: "private_mountain_transportation",
    launch: { status: "opening_announced", date: "2026-11-15" },
    authority: ["big_sky_service_information", "published_transfer_pricing", "site_booking_state"],
  },
  {
    dcc_id: "dcc:site:save-on-the-strip",
    id: "save-on-the-strip",
    name: "Save On The Strip",
    url: "https://saveonthestrip.com",
    type: "las_vegas_travel_planning",
    authority: ["las_vegas_destination_content"],
  },
  {
    dcc_id: "dcc:site:welcome-to-the-swamp",
    id: "welcome-to-the-swamp",
    name: "Welcome to the Swamp",
    url: "https://welcometotheswamp.com",
    type: "swamp_tour_discovery",
    authority: ["swamp_tour_discovery", "new_orleans_swamp_experience_context"],
  },
  {
    dcc_id: "dcc:site:juneau-flight-deck",
    id: "juneau-flight-deck",
    name: "Juneau Flight Deck",
    url: "https://juneauflightdeck.com",
    type: "juneau_excursion_discovery",
    authority: ["juneau_excursion_context"],
  },
  {
    dcc_id: "dcc:site:shuttleya",
    id: "shuttleya",
    name: "ShuttleYa",
    url: "https://shuttleya.com",
    type: "transportation_discovery",
    authority: ["transportation_discovery_content"],
  },
  {
    dcc_id: "dcc:site:420-friendly-airport-pickup",
    id: "420-friendly-airport-pickup",
    name: "420 Friendly Airport Pickup",
    url: "https://420friendlyairportpickup.com",
    type: "private_airport_transportation_discovery",
    authority: ["airport_transfer_content", "dispensary_stop_trip_context"],
  },
] as const;

export const DCC_PORTFOLIO_RELATIONSHIPS = [
  { from: "dcc:site:destination-command-center", relation: "indexes", to: "dcc:site:cruise-promenade" },
  { from: "dcc:site:destination-command-center", relation: "indexes", to: "dcc:site:vibe-around-town" },
  { from: "dcc:site:destination-command-center", relation: "indexes", to: "dcc:site:wno-tours" },
  { from: "dcc:site:destination-command-center", relation: "indexes", to: "dcc:site:gosno" },
  { from: "dcc:site:destination-command-center", relation: "indexes", to: "dcc:site:bigsky-gosno" },
  { from: "dcc:site:bigsky-gosno", relation: "related_service", to: "dcc:site:gosno" },
  { from: "dcc:site:wno-tours", relation: "serves_destination", to: "dcc:destination:new-orleans" },
  { from: "dcc:site:welcome-to-the-swamp", relation: "serves_destination", to: "dcc:destination:new-orleans" },
  { from: "dcc:site:vibe-around-town", relation: "serves_destination", to: "dcc:destination:st-thomas" },
  { from: "dcc:site:vibe-around-town", relation: "serves_destination", to: "dcc:destination:st-john" },
  { from: "dcc:site:vibe-around-town", relation: "serves_destination", to: "dcc:destination:st-croix" },
  { from: "dcc:site:gosno", relation: "serves_airport", to: "dcc:airport:den" },
  { from: "dcc:site:gosno", relation: "serves_airport", to: "dcc:airport:cos" },
  { from: "dcc:site:bigsky-gosno", relation: "serves_airport", to: "dcc:airport:bzn" },
  { from: "dcc:site:bigsky-gosno", relation: "serves_destination", to: "dcc:destination:big-sky-montana" },
] as const;
