import { HUBS, RIVER_OPS_OUTBOUND_TARGETS, RIVER_OPS_TERMINAL, SITE_URL } from "@/lib/content";

export const dynamic = "force-static";

export function GET() {
  const body = [
    "# Welcome to the Dells",
    "",
    "> Welcome to the Dells is a consumer-first Wisconsin Dells planning and discovery site.",
    "",
    "DCC ID: dcc:site:welcome-to-the-dells",
    "DCC contract: dcc-site-contract v1.1",
    "Canonical DCC truth record: https://www.destinationcommandcenter.com/api/public/truth-feed?id=welcome-to-the-dells",
    "Last verified: 2026-08-24",
    "",
    "## What this site helps with",
    "- Things to do in Wisconsin Dells",
    "- Wisconsin Dells boat tours and Original Wisconsin Ducks",
    "- Wisconsin Dells waterpark planning",
    "- Rainy-day and indoor activities",
    "- Family trips",
    "- Adults-only and couples trips",
    "- Tonight and after-dark plans",
    "- Downtown, Wisconsin Dells Parkway, and Lake Delton area decisions",
    "- Large-group activity and meal logistics",
    "",
    "## Canonical consumer pages",
    `- ${SITE_URL}/`,
    `- ${SITE_URL}/things-to-do`,
    `- ${SITE_URL}/boat-tours`,
    `- ${SITE_URL}/waterparks`,
    `- ${SITE_URL}/first-time`,
    `- ${SITE_URL}/rainy-day`,
    `- ${SITE_URL}/families`,
    `- ${SITE_URL}/adults`,
    `- ${SITE_URL}/tonight`,
    `- ${SITE_URL}/large-groups`,
    `- ${SITE_URL}/downtown`,
    `- ${SITE_URL}/parkway`,
    `- ${SITE_URL}/lake-delton`,
    "",
    "## Planning model",
    "- Start with one anchor experience: river, waterpark, major attraction, or evening plan.",
    "- Keep nearby activities together instead of repeatedly crossing town.",
    "- Preserve a weather backup, especially for outdoor and river plans.",
    "- Use current operator or marketplace booking pages for live price, availability, departure time, and final terms.",
    "",
    "## Signature river experiences",
    ...RIVER_OPS_TERMINAL.map((card) => `- ${card.title}: ${card.loungeIntel} CTA: ${card.ctaLabel}.`),
    "",
    "## Areas",
    ...HUBS.map((hub) => `- ${hub.name}: ${hub.oneLine} ${hub.defaultMove}`),
    "",
    "## Booking and commercial behavior",
    `- Stable outbound pattern: ${SITE_URL}/out/wisconsin-dells/{slug}`,
    "- Controlled operator links lead to the relevant operator ticket path when available.",
    "- Viator inventory is used as a marketplace fallback where applicable.",
    "- The site does not invent live prices, availability, departure times, or cancellation terms.",
    ...RIVER_OPS_OUTBOUND_TARGETS.map(
      (target) => `- ${target.slug}: ${target.operator}; ${target.routeKind}; provider ${target.provider}.`,
    ),
    "",
    "## Destination Command Center relationship",
    "- Destination Command Center provides broader Wisconsin Dells destination context.",
    "- Welcome to the Dells is the consumer-facing local discovery and decision layer.",
    "- Visitors may move between the two when deeper destination research is useful.",
    "- Portfolio identity/status claims should resolve to the canonical DCC truth record above.",
    "",
    "## Machine-readable entry points",
    `- ${SITE_URL}/agent.json`,
    `- ${SITE_URL}/llms.txt`,
    `- ${SITE_URL}/sitemap.xml`,
    `- ${SITE_URL}/robots.txt`,
    "- https://www.destinationcommandcenter.com/api/public/truth-feed?id=welcome-to-the-dells",
    "",
  ].join("\n");

  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600, s-maxage=3600",
    },
  });
}
