import { NextRequest, NextResponse } from "next/server";

const ORIGIN = "https://destinationcommandcenter.com";

export function proxy(request: NextRequest) {
  const { pathname, search } = request.nextUrl;

  // Preserve origin-root assets generated by the upstream Next.js app.
  if (
    pathname.startsWith("/_next/") ||
    pathname.startsWith("/images/") ||
    pathname === "/ga-init.js" ||
    pathname === "/favicon.ico"
  ) {
    return NextResponse.rewrite(new URL(`${pathname}${search}`, ORIGIN));
  }

  // Upstream New Orleans links already carry this prefix.
  if (pathname === "/new-orleans" || pathname.startsWith("/new-orleans/")) {
    return NextResponse.rewrite(new URL(`${pathname}${search}`, ORIGIN));
  }

  // Keep the public WNO root and legacy WNO-style paths on the WNO hostname.
  const destination = pathname === "/" ? "/new-orleans" : `/new-orleans${pathname}`;
  return NextResponse.rewrite(new URL(`${destination}${search}`, ORIGIN));
}

export const config = {
  matcher: ["/((?!agent\\.json$|llms\\.txt$).*)"],
};
