import type { NetworkNodeConfig } from "./types";

export const NETWORK_NODE_REGISTRY = [
  {
    id: "dcc",
    displayName: "Destination Command Center",
    domains: [
      "destinationcommandcenter.com",
      "www.destinationcommandcenter.com",
      "destinations-cc.vercel.app",
    ],
    routePatterns: [
      { pattern: "/", intent: "dcc-home" },
      { pattern: "/network", intent: "network-governance" },
      { pattern: "/command", intent: "command-console" },
      { pattern: "/internal/*", intent: "internal-control-plane" },
      { pattern: "/operator/*", intent: "operator-control-plane" },
      { pattern: "/dashboard/*", intent: "ops-dashboard" },
      { pattern: "/admin/*", intent: "admin-control-plane" },
      { pattern: "/privacy", intent: "dcc-legal" },
      { pattern: "/terms", intent: "dcc-legal" },
      { pattern: "/about", intent: "dcc-public-info" },
      { pattern: "/contact", intent: "dcc-public-info" },
      { pattern: "/ai", intent: "dcc-public-info" },
      { pattern: "/system", intent: "system-map" },
      { pattern: "/network-health", intent: "network-health" },
      { pattern: "/agent.json", intent: "machine-readable" },
      { pattern: "/llms.txt", intent: "machine-readable" },
    ],
    hue: {
      name: "cobalt-tangerine-command",
      primaryAccent: "#2563eb",
      secondaryAccent: "#f97316",
      localAccent: "#38bdf8",
      surfaceTone: "command",
    },
    brandMode: "dcc-core",
    navItems: ["Overview", "Routing", "Metrics", "Governance"],
    primaryCta: "Launch Console",
    footerTrustLine: "Destination Command Center network governance.",
  },
  {
    id: "wtonot",
    displayName: "Welcome to New Orleans Tours",
    domains: ["welcometoneworleanstours.com", "www.welcometoneworleanstours.com"],
    routePatterns: [
      { pattern: "/new-orleans/tours", intent: "tourism-storefront" },
      { pattern: "/new-orleans/food", intent: "food-cocktail-tours" },
      { pattern: "/new-orleans/music", intent: "music-nightlife-tours" },
      { pattern: "/new-orleans/neighborhoods", intent: "local-guide" },
      { pattern: "/new-orleans/things-to-do", intent: "city-guide" },
      { pattern: "/new-orleans/weekend-guide", intent: "itinerary-guide" },
    ],
    hue: {
      name: "new-orleans-brass-purple",
      primaryAccent: "#d8a84f",
      secondaryAccent: "#f97316",
      localAccent: "#6d3bbd",
      surfaceTone: "warm-dark",
    },
    brandMode: "tourism-storefront",
    navItems: ["Find My Tour", "Swamp", "History", "Food", "Night Tours"],
    primaryCta: "Check Availability",
    footerTrustLine: "Part of the Destination Command Center network.",
  },
  {
    id: "wts",
    displayName: "Welcome to the Swamp",
    domains: ["welcometotheswamp.com", "www.welcometotheswamp.com"],
    routePatterns: [
      { pattern: "/new-orleans/swamp-tours", intent: "swamp-tour-hub" },
      { pattern: "/new-orleans/swamp-tours/*", intent: "swamp-tour-guide" },
      { pattern: "/new-orleans/airboat-vs-swamp-tour", intent: "airboat-vs-boat" },
      { pattern: "/new-orleans/best-swamp-tour", intent: "swamp-tour-comparison" },
      { pattern: "/new-orleans/family-friendly", intent: "family-swamp-tours" },
      { pattern: "/new-orleans/plantation-tours", intent: "plantation-and-swamp-context" },
      { pattern: "/new-orleans/swamp-tour-with-kids", intent: "with-kids" },
    ],
    hue: {
      name: "bayou-green-brass",
      primaryAccent: "#37c889",
      secondaryAccent: "#f4b74f",
      localAccent: "#173f35",
      surfaceTone: "natural-dark",
    },
    brandMode: "decision-helper",
    navItems: ["Airboat vs Boat", "With Kids", "Best Time", "Transportation", "Types"],
    primaryCta: "Plan Your Tour",
    footerTrustLine: "A governed swamp-tour decision node in the DCC network.",
  },
  {
    id: "jfd",
    displayName: "Juneau Flight Deck",
    domains: ["juneauflightdeck.com", "www.juneauflightdeck.com"],
    routePatterns: [
      { pattern: "/juneau", intent: "juneau-hub" },
      { pattern: "/juneau/*", intent: "juneau-shore-excursion" },
      { pattern: "/juneau-whale-watching-from-port", intent: "whale-watch-from-port" },
      { pattern: "/skagway/*", intent: "alaska-port-excursion" },
      { pattern: "/sitka/*", intent: "alaska-port-excursion" },
      { pattern: "/ketchikan/*", intent: "alaska-port-excursion" },
    ],
    hue: {
      name: "glacier-blue-aviation",
      primaryAccent: "#38bdf8",
      secondaryAccent: "#f59e0b",
      localAccent: "#0f3a5f",
      surfaceTone: "alpine-dark",
    },
    brandMode: "decision-helper",
    navItems: ["Helicopter", "Whales", "Cruise Port", "Weather", "Backups"],
    primaryCta: "Find My Excursion",
    footerTrustLine: "Juneau shore-day planning governed by DCC.",
  },
  {
    id: "wta",
    displayName: "Welcome to Alaska Tours",
    domains: ["welcometoalaskatours.com", "www.welcometoalaskatours.com"],
    routePatterns: [
      { pattern: "/alaska", intent: "alaska-tour-hub" },
      { pattern: "/alaska/*", intent: "alaska-tour-guide" },
    ],
    hue: {
      name: "alaska-navy-glacier",
      primaryAccent: "#60a5fa",
      secondaryAccent: "#fbbf24",
      localAccent: "#d9f99d",
      surfaceTone: "alpine-dark",
    },
    brandMode: "tourism-storefront",
    navItems: ["Whales", "Glaciers", "Cruise Port", "Weather", "Plan"],
    primaryCta: "Plan Alaska Tours",
    footerTrustLine: "An Alaska tours node governed by DCC.",
  },
  {
    id: "gosno",
    displayName: "GoSno",
    domains: ["gosno.co", "www.gosno.co"],
    routePatterns: [
      { pattern: "/transportation/colorado", intent: "colorado-transport-hub" },
      { pattern: "/transportation/colorado/*", intent: "colorado-transfer-guide" },
      { pattern: "/denver-to-mountains", intent: "mountain-transfer-hub" },
      { pattern: "/denver-to-mountains/*", intent: "mountain-transfer-guide" },
      { pattern: "/breckenridge-vs-vail", intent: "resort-comparison" },
      { pattern: "/shuttle-vs-driving-breckenridge", intent: "transfer-comparison" },
      { pattern: "/can-you-get-to-breckenridge-without-a-car", intent: "car-free-transfer" },
    ],
    hue: {
      name: "alpine-blue-ice",
      primaryAccent: "#60a5fa",
      secondaryAccent: "#f97316",
      localAccent: "#e0f2fe",
      surfaceTone: "alpine-dark",
    },
    brandMode: "transport-execution",
    navItems: ["Airport Shuttle", "Breckenridge", "Vail", "Destinations", "Book"],
    primaryCta: "Start Transfer",
    footerTrustLine: "Mountain transfer execution governed by DCC.",
  },
  {
    id: "apex",
    displayName: "Apex Limo",
    domains: ["welcometoapexlimo.com", "www.welcometoapexlimo.com"],
    routePatterns: [],
    hue: {
      name: "premium-black-cobalt",
      primaryAccent: "#2563eb",
      secondaryAccent: "#d8a84f",
      localAccent: "#e5e7eb",
      surfaceTone: "premium-dark",
    },
    brandMode: "transport-execution",
    navItems: ["Airport", "Private SUV", "Groups", "Events", "Quote"],
    primaryCta: "Request Ride",
    footerTrustLine: "Premium transport node governed by DCC.",
  },
  {
    id: "somerset",
    displayName: "Somerset VIP Shuttle",
    domains: ["shuttletosomersetamphitheater.com", "www.shuttletosomersetamphitheater.com"],
    routePatterns: [
      { pattern: "/somerset-wi", intent: "somerset-home" },
      { pattern: "/somerset-wi/*", intent: "somerset-guide" },
    ],
    hue: {
      name: "concert-gold-forest",
      primaryAccent: "#f4b74f",
      secondaryAccent: "#37c889",
      localAccent: "#17291f",
      surfaceTone: "natural-dark",
    },
    brandMode: "transport-execution",
    navItems: ["Concert Shuttle", "Camping", "Groups", "Pickup", "Book"],
    primaryCta: "Plan Shuttle",
    footerTrustLine: "Somerset shuttle planning governed by DCC.",
  },
  {
    id: "blue-hills",
    displayName: "Blue Hills Outpost",
    domains: ["bluehillsoutpost.com", "www.bluehillsoutpost.com"],
    routePatterns: [
      { pattern: "/western-wisconsin", intent: "western-wisconsin-hub" },
      { pattern: "/western-wisconsin/*", intent: "western-wisconsin-guide" },
    ],
    hue: {
      name: "outpost-forest-cream",
      primaryAccent: "#4ade80",
      secondaryAccent: "#f4b74f",
      localAccent: "#f5f1df",
      surfaceTone: "natural-dark",
    },
    brandMode: "tourism-storefront",
    navItems: ["Stays", "Activities", "Weekend", "Fall", "Plan"],
    primaryCta: "Plan the Outpost",
    footerTrustLine: "Western Wisconsin local-help node governed by DCC.",
  },
  {
    id: "dells",
    displayName: "Welcome to the Dells",
    domains: ["welcometothedells.com", "www.welcometothedells.com"],
    routePatterns: [
      { pattern: "/wisconsin-dells-bachelorette-party-food", intent: "dells-group-food" },
      { pattern: "/wisconsin-dells-large-group-dinner", intent: "dells-group-food" },
    ],
    hue: {
      name: "dells-water-tangerine",
      primaryAccent: "#22d3ee",
      secondaryAccent: "#f97316",
      localAccent: "#a7f3d0",
      surfaceTone: "warm-dark",
    },
    brandMode: "decision-helper",
    navItems: ["Things To Do", "River Ops", "Groups", "Food", "Plan"],
    primaryCta: "Plan the Dells",
    footerTrustLine: "Wisconsin Dells decision node governed by DCC.",
  },
  {
    id: "shuttleya",
    displayName: "Shuttleya",
    domains: ["shuttleya.com", "www.shuttleya.com"],
    routePatterns: [
      { pattern: "/mighty-argo", intent: "argo-hub" },
      { pattern: "/mighty-argo/*", intent: "argo-guide" },
      { pattern: "/mighty-argo-shuttle", intent: "argo-shuttle" },
      { pattern: "/argo-parking-vs-shuttle", intent: "argo-comparison" },
      { pattern: "/denver-to-argo-transportation", intent: "argo-transfer" },
      { pattern: "/how-to-get-to-argo-cable-car-from-denver", intent: "argo-transfer" },
    ],
    hue: {
      name: "shuttle-cobalt-gold",
      primaryAccent: "#2563eb",
      secondaryAccent: "#f4b74f",
      localAccent: "#93c5fd",
      surfaceTone: "premium-dark",
    },
    brandMode: "transport-execution",
    navItems: ["Argo", "Airport", "Red Rocks", "Events", "Book"],
    primaryCta: "Reserve Shuttle",
    footerTrustLine: "Shuttle execution node governed by DCC.",
  },
  {
    id: "redrocksfastpass",
    displayName: "Red Rocks Fast Pass",
    domains: ["redrocksfastpass.com", "www.redrocksfastpass.com"],
    routePatterns: [
      { pattern: "/red-rocks", intent: "red-rocks-hub" },
      { pattern: "/red-rocks/*", intent: "red-rocks-guide" },
      { pattern: "/red-rocks-shuttle", intent: "red-rocks-shuttle" },
      { pattern: "/red-rocks-transportation", intent: "red-rocks-transport" },
      { pattern: "/red-rocks-events", intent: "red-rocks-events" },
      { pattern: "/red-rocks-events/*", intent: "red-rocks-event" },
      { pattern: "/red-rocks-shuttle-vs-uber", intent: "red-rocks-comparison" },
      { pattern: "/best-way-to-get-to-red-rocks-from-denver", intent: "red-rocks-transport" },
      { pattern: "/best-way-to-leave-red-rocks", intent: "red-rocks-exit" },
    ],
    hue: {
      name: "red-rocks-tangerine-night",
      primaryAccent: "#f97316",
      secondaryAccent: "#2563eb",
      localAccent: "#fed7aa",
      surfaceTone: "warm-dark",
    },
    brandMode: "operator-checkout",
    navItems: ["Shows", "Shuttle", "Pickup", "Private", "Book"],
    primaryCta: "Book Red Rocks",
    footerTrustLine: "Red Rocks transport node governed by DCC.",
  },
  {
    id: "saveonthestrip",
    displayName: "Save On The Strip",
    domains: ["saveonthestrip.com", "www.saveonthestrip.com"],
    routePatterns: [
      { pattern: "/las-vegas", intent: "vegas-hub" },
      { pattern: "/las-vegas/*", intent: "vegas-guide" },
      { pattern: "/vegas", intent: "vegas-hub" },
      { pattern: "/vegas/*", intent: "vegas-guide" },
      { pattern: "/fremont-street", intent: "vegas-guide" },
      { pattern: "/things-to-do-on-the-strip", intent: "vegas-guide" },
    ],
    hue: {
      name: "vegas-neon-cobalt",
      primaryAccent: "#a855f7",
      secondaryAccent: "#f97316",
      localAccent: "#22d3ee",
      surfaceTone: "warm-dark",
    },
    brandMode: "marketplace",
    navItems: ["Deals", "Hotels", "Shows", "Tours", "Contact"],
    primaryCta: "Find Deals",
    footerTrustLine: "Vegas deal-routing node governed by DCC.",
  },
  {
    id: "sedona-jeep",
    displayName: "Sedona Jeep Tours",
    domains: ["sedonajeeptours.com", "www.sedonajeeptours.com"],
    routePatterns: [{ pattern: "/sedona/jeep-tours", intent: "sedona-jeep-decision" }],
    hue: {
      name: "sedona-red-sky",
      primaryAccent: "#f97316",
      secondaryAccent: "#38bdf8",
      localAccent: "#b91c1c",
      surfaceTone: "warm-dark",
    },
    brandMode: "decision-helper",
    navItems: ["Jeep Tours", "Views", "Timing", "Fit", "Book"],
    primaryCta: "Find Jeep Tour",
    footerTrustLine: "Sedona tour decision node governed by DCC.",
  },
  {
    id: "lake-tahoe",
    displayName: "Lake Tahoe Transport",
    domains: ["laketahoetransport.com", "www.laketahoetransport.com"],
    routePatterns: [{ pattern: "/lake-tahoe/things-to-do", intent: "tahoe-activities" }],
    hue: {
      name: "tahoe-blue-pine",
      primaryAccent: "#38bdf8",
      secondaryAccent: "#37c889",
      localAccent: "#e0f2fe",
      surfaceTone: "alpine-dark",
    },
    brandMode: "transport-execution",
    navItems: ["Things To Do", "Transport", "Weather", "Groups", "Plan"],
    primaryCta: "Plan Tahoe",
    footerTrustLine: "Lake Tahoe planning node governed by DCC.",
  },
  {
    id: "marketplace-generic",
    displayName: "DCC Marketplace Guide",
    domains: [],
    routePatterns: [
      { pattern: "/cruises", intent: "cruise-marketplace" },
      { pattern: "/cruises/*", intent: "cruise-marketplace" },
      { pattern: "/ports", intent: "port-marketplace" },
      { pattern: "/ports/*", intent: "port-marketplace" },
      { pattern: "/hotel/*", intent: "hotel-marketplace" },
      { pattern: "/hotels-near/*", intent: "hotel-marketplace" },
      { pattern: "/casino/*", intent: "casino-marketplace" },
      { pattern: "/venues", intent: "venue-marketplace" },
      { pattern: "/venues/*", intent: "venue-marketplace" },
      { pattern: "/tours", intent: "tour-marketplace" },
      { pattern: "/tours/*", intent: "tour-marketplace" },
    ],
    hue: {
      name: "network-marketplace-cobalt",
      primaryAccent: "#2563eb",
      secondaryAccent: "#f97316",
      localAccent: "#94a3b8",
      surfaceTone: "command",
    },
    brandMode: "marketplace",
    navItems: ["Guide", "Compare", "Routes", "Tours", "Continue"],
    primaryCta: "Compare Options",
    footerTrustLine: "Marketplace guidance governed by DCC.",
  },
] as const satisfies readonly NetworkNodeConfig[];

export type RegisteredNetworkNode = (typeof NETWORK_NODE_REGISTRY)[number];

export const NETWORK_NODE_BY_ID = Object.fromEntries(
  NETWORK_NODE_REGISTRY.map((node) => [node.id, node]),
) as Record<RegisteredNetworkNode["id"], RegisteredNetworkNode>;
